[package]
name = "rzup"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.4", features = ["derive"] }
dirs = "5.0.1"
downloader = { version = "0.2.7", default-features = false, features = [
  "rustls-tls",
] }
flate2 = "1.0.30"
fs_extra = "1.3.0"
reqwest = { version = "0.11", default-features = false, features = [
    "json",
    "rustls-tls",
] }
reqwest-middleware = "0.3.1"
reqwest-retry = "0.5.0"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
tar = "0.4.40"
tempfile = "3.10.1"
tokio = { version = "1.37.0", features = ["full", "rt"] }
xz = "0.1.0"
